<?php

/**
 * Implements hook_preprocess_paragraph().
 */
function winner_component_preprocess_paragraph(array &$variables) {
    if ($variables['paragraph']->bundle() === 'promo_smt') {
      $variables['#attached']['library'][] = 'winner_component/winner_component_markup_smt';
    }
    \Drupal::logger('my_custom_module')->notice('My custom module is working! This is a test log.');
    $variables['attributes']['width'] = NULL;
    $variables['attributes']['height'] = NULL;
  }